config/routes.rb
Rails.application.routes.draw do
  
	resources :medicamentos do 
	    member do
	      get :aumentar_estoque
	      patch :grava_aumento_estoque
	    end

	    collection do
	      get :vencidos
	      get :disponiveis
	    end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medicamento.rb
class Medicamento < ApplicationRecord

	# SCOPES
	scope :vencidos, ->	{ where('validade <= ?', Date.current) }
	scope :disponiveis, ->	{ where('validade >= ? AND estoque > ?', Date.current, 0) }


	# CALLBACKS
	before_save :bota_tudo_em_maiusculo

	

	private
	
		def bota_tudo_em_maiusculo
			self.nome = nome.upcase
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/medicamentos_controller.rb
class MedicamentosController < ApplicationController
  before_action :set_medicamento, only: [:show, :edit, :update, :destroy, :aumentar_estoque, :grava_aumento_estoque]

  # GET /medicamentos
  # GET /medicamentos.json
  def index
    @medicamentos = Medicamento.all
  end

  # GET /medicamentos/1
  # GET /medicamentos/1.json
  def show
  end

  def vencidos
    @medicamentos = Medicamento.vencidos
  end
  
  def disponiveis
    @medicamentos = Medicamento.disponiveis
  end

  # GET /medicamentos/new
  def new
    @medicamento = Medicamento.new
  end

  # GET /medicamentos/1/edit
  def edit
  end

  # POST /medicamentos
  # POST /medicamentos.json
  def create
    @medicamento = Medicamento.new(medicamento_params)

    respond_to do |format|
      if @medicamento.save
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully created.' }
        format.json { render :show, status: :created, location: @medicamento }
      else
        format.html { render :new }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicamentos/1
  # PATCH/PUT /medicamentos/1.json
  def update
    respond_to do |format|
      if @medicamento.update(medicamento_params)
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicamento }
      else
        format.html { render :edit }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicamentos/1
  # DELETE /medicamentos/1.json
  def destroy
    @medicamento.destroy
    respond_to do |format|
      format.html { redirect_to medicamentos_url, notice: 'Medicamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def aumentar_estoque
    
  end

  def grava_aumento_estoque
    incremento = params[:add_estoque].to_i

    if incremento > 0
      @medicamento.estoque += incremento
      @medicamento.save
      redirect_to medicamentos_url, notice: 'Estoque aumentado'
    else
      flash[:error] = 'Valor Negativo'
      render :aumentar_estoque
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicamento
      @medicamento = Medicamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicamento_params
      params.require(:medicamento).permit(:nome, :estoque, :validade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicamentos_helper.rb
module MedicamentosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MedicamentosCM" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="container">

    <%= bootstrap_flash %>
    <%= yield %>

  </body>
</html>

app/views/medicamento/_form.html.erb
<%= simple_form_for @medicamento, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nome %>
  <%= error_span(@medicamento[:nome]) %>
  <%= f.input :estoque %>
  <%= error_span(@medicamento[:estoque]) %>
  <%= f.input :validade %>
  <%= error_span(@medicamento[:validade]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                medicamentos_path, :class => 'btn btn-default' %>
<% end %>

app/views/medicamento/edit.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicamento/index.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:estoque) %></th>
      <th><%= model_class.human_attribute_name(:validade) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= link_to medicamento.id, medicamento_path(medicamento) %></td>
        <td><%= medicamento.nome %></td>
        <td><%= medicamento.estoque %></td>
        <td><%= medicamento.validade %></td>
        <td><%=l medicamento.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medicamento_path(medicamento), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medicamento_path(medicamento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_medicamento_path,
            :class => 'btn btn-primary' %>

app/views/medicamento/new.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/medicamento/show.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @medicamento.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estoque) %>:</strong></dt>
  <dd><%= @medicamento.estoque %></dd>
  <dt><strong><%= model_class.human_attribute_name(:validade) %>:</strong></dt>
  <dd><%= @medicamento.validade %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              medicamentos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_medicamento_path(@medicamento), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              medicamento_path(@medicamento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/medicamentos/_form.html.erb
<div class="form_for">
  <%= form_for(medicamento) do |f| %>
    <% if medicamento.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(medicamento.errors.count, "error") %> prohibited this medicamento from being saved:</h2>

        <ul>
        <% medicamento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :nome %>
      <%= f.text_field :nome %>
    </div>

    <div class="field">
      <%= f.label :estoque %>
      <%= f.number_field :estoque %>
    </div>

    <div class="field">
      <%= f.label :validade %>
      <%= f.date_select :validade %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/medicamentos/aumentar_estoque.html.erb
<div class="page-header">
	<h4>Aumentar o estoque do medicamento: <br /><%= @medicamento.nome -%> (<%= @medicamento.estoque -%>)</h4>
</div>


<%= form_tag grava_aumento_estoque_medicamento_path(@medicamento), :class => "form-vertical", method: :patch do %>
	<label for="">
		Quantidade Adicional: 
	</label>
	<%= text_field_tag :add_estoque, 0, class: 'form-control', type: :number -%>
	<hr>
	<%= submit_tag 'Arrocha!', class: 'btn btn-primary' -%>
<% end -%>

app/views/medicamentos/disponiveis.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_medicamento_path, :class => 'btn btn-primary pull-right' %>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:estoque) %></th>
      <th><%= model_class.human_attribute_name(:validade) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= link_to medicamento.id, medicamento_path(medicamento) %></td>
        <td><%= medicamento.nome %></td>
        <td><%= medicamento.estoque %></td>
        <td><%=l medicamento.validade if medicamento.validade.present? %></td>
        <td><%=l medicamento.created_at %></td>
        <td>
          <%= link_to "Aumentar Estoque", aumentar_estoque_medicamento_path(medicamento), class: 'btn btn-info btn-xs' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medicamento_path(medicamento), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medicamento_path(medicamento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/medicamentos/edit.html.erb
<h1>Editing Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Show', @medicamento %> |
<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/index.html.erb
<%- model_class = Medicamento -%>
<div class="page-header">
  <%= link_to t('.new', :default => t("helpers.links.new")), new_medicamento_path, :class => 'btn green right white-text text-darken-2'%>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:estoque) %></th>
      <th><%= model_class.human_attribute_name(:validade) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= link_to medicamento.id, medicamento_path(medicamento) %></td>
        <td><%= medicamento.nome %></td>
        <td><%= medicamento.estoque %></td>
        <td><%=l medicamento.validade %></td>
        <td>
          <%= link_to "+", aumentar_estoque_medicamento_path(medicamento), class: 'btn-floating white blue-text text-darken-2' do %> <i class="material-icons">add</i> <% end %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_medicamento_path(medicamento), :class => 'btn-floating white blue-text text-darken-2' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      medicamento_path(medicamento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza?')) },
                      :class => 'btn-floating white blue-text text-darken-2' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/medicamentos/new.html.erb
<h1>New Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @medicamento.nome %>
</p>

<p>
  <strong>Estoque:</strong>
  <%= @medicamento.estoque %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @medicamento.validade %>
</p>

<%= link_to 'Edit', edit_medicamento_path(@medicamento) %> |
<%= link_to 'Back', medicamentos_path %>